name = "pars-mars"
main = "dist/worker.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-04-01"

[build]
command = "npm run build && npx @cloudflare/next-on-pages@1"
cwd = "./"
upload.format = "modules"

[[d1_databases]]
binding = "DB"
database_name = "pasrmars"
database_id = "bce0b3ca-0cdd-4233-8a31-ff1295b51c7e"