name = "pars-mars"
main = "dist/worker.js"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
compatibility_date = "2024-04-01"

[build]
command = "npm run build && npx @cloudflare/next-on-pages@1"
cwd = "./"
upload.format = "modules"